package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSupplierPlatform;
import org.linlinjava.litemall.db.domain.LitemallSupplierPlatformExample;

public interface LitemallSupplierPlatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    long countByExample(LitemallSupplierPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSupplierPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    int insert(LitemallSupplierPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSupplierPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    LitemallSupplierPlatform selectOneByExample(LitemallSupplierPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    LitemallSupplierPlatform selectOneByExampleSelective(@Param("example") LitemallSupplierPlatformExample example, @Param("selective") LitemallSupplierPlatform.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    List<LitemallSupplierPlatform> selectByExampleSelective(@Param("example") LitemallSupplierPlatformExample example, @Param("selective") LitemallSupplierPlatform.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    List<LitemallSupplierPlatform> selectByExample(LitemallSupplierPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    LitemallSupplierPlatform selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSupplierPlatform.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    LitemallSupplierPlatform selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    LitemallSupplierPlatform selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSupplierPlatform record, @Param("example") LitemallSupplierPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSupplierPlatform record, @Param("example") LitemallSupplierPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSupplierPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSupplierPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallSupplierPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_supplier_platform
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}